
resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/kalaiganeshan/concourse.git
      branch: master
  - name: time
    type: time
    source:
      interval: 60s


jobs:
  - name: maven-package
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
      - get: time
    

    - task: maven-package
      privileged: true
      file: concourse/pipeline/build.yml
    - task: rename-file
      file: concourse/pipeline/rename-file.yml

 # - name: rename file
   # plan:
   # - aggregate:
     # - get: jar-file
       ##   passed: [maven-package]
    #  - get: time
   # - task: rename-file
    # file: concourse/pipeline/rename-file.yml
