---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: maven
    tag: latest
    
inputs:
  - name: git-repo
  
outputs:
  - name: resource-app
  
run:
  path: concourse/pipeline/build.sh
